<?php declare(strict_types=1); $title = 'Foglalás – A Bata'; require __DIR__ . '/_layout_start.php'; $e = static fn (mixed $v): string => htmlspecialchars((string) $v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); ?>
<article class="admin-page detail" aria-labelledby="detail-title"><p><a href="/admin/bookings">← Vissza a listához</a></p><p class="eyebrow">Foglalás</p><h1 id="detail-title"><?= $e($booking['reference']) ?></h1><p><span class="status status-<?= $e($booking['status']) ?>"><?= $e(\App\Presentation\BookingStatusLabel::for((string) $booking['status'])) ?></span></p>
<section><h2>Vendég és időszak</h2><dl class="facts"><?php foreach (['contact_name'=>'Kapcsolattartó','email'=>'E-mail','phone'=>'Telefon','arrival_date'=>'Érkezés','departure_date'=>'Távozás','nights'=>'Éjszakák','adults'=>'Felnőttek','children'=>'Gyermekek','notes'=>'Megjegyzés','created_at'=>'Létrehozva','updated_at'=>'Frissítve'] as $key=>$label): ?><div><dt><?= $label ?></dt><dd><?= $e($booking[$key] ?? '—') ?></dd></div><?php endforeach ?><div><dt>Gyermekéletkorok</dt><dd><?= $e(implode(', ', $booking['children_ages'] ?? [])) ?: '—' ?></dd></div></dl></section>
<section><h2>Adatkezelési tájékoztató</h2><dl class="facts"><div><dt>Elfogadva</dt><dd><?= $e($booking['privacy_accepted_at'] ?? '—') ?></dd></div><div><dt>Verzió</dt><dd><?= $e($booking['privacy_policy_version'] ?? '—') ?></dd></div><div><dt>URL</dt><dd><?php if (!empty($booking['privacy_policy_url'])): ?><a href="<?= $e($booking['privacy_policy_url']) ?>" rel="noopener noreferrer"><?= $e($booking['privacy_policy_url']) ?></a><?php else: ?>—<?php endif ?></dd></div></dl></section>
<?php if (!empty($booking['legacy_source_system'])): ?><section><h2>Régi rendszer forrása</h2><dl class="facts"><div><dt>Forrás</dt><dd>Régi WP Booking System</dd></div><div><dt>Régi foglalás azonosító</dt><dd><?= $e($booking['legacy_source_booking_id']) ?></dd></div><div><dt>Régi státusz</dt><dd><?= $e($booking['legacy_source_status']) ?></dd></div><div><dt>Importálva</dt><dd><?= $e($booking['legacy_imported_at']) ?></dd></div><div><dt>Áradat</dt><dd>nem állt rendelkezésre</dd></div></dl></section><?php endif; ?><section><h2>Ár-pillanatkép</h2><?php if (!empty($booking['legacy_pricing_unavailable'])): ?><p class="alert">Áradat nem érhető el a régi rendszer exportjában.</p><?php else: ?><p class="total"><?= $e(\App\Presentation\HufFormatter::format($booking['total_amount'])) ?></p><?php endif; ?><?php $snapshot=$booking['pricing_snapshot'] ?? []; ?><dl class="facts"><?php foreach (['pricing_base'=>'Árképzési alap','nights'=>'Éjszakák','persons'=>'Személyek','unit_price'=>'Egységár'] as $key=>$label): if (isset($snapshot[$key])): ?><div><dt><?= $label ?></dt><dd><?= $e($key === 'unit_price' ? \App\Presentation\HufFormatter::format($snapshot[$key]) : (is_array($snapshot[$key]) ? implode(', ', $snapshot[$key]) : $snapshot[$key])) ?></dd></div><?php endif; endforeach ?></dl></section>
<?php if (($snapshot['pricing_mode'] ?? null)==='occupancy'): ?><section><h2>Foglalói létszám és occupancy árképzés</h2><dl class="facts"><div><dt>Árazási létszám</dt><dd><?= $e($snapshot['chargeable_guests'] ?? '') ?></dd></div><div><dt>Tényleges vendégek</dt><dd><?= $e($snapshot['physical_guests'] ?? '') ?></dd></div><div><dt>Ingyenes gyermekek (0–3)</dt><dd><?= $e(implode(', ', $snapshot['free_children'] ?? [])) ?: 'nincs' ?></dd></div><div><dt>Egyéjszakás felár</dt><dd><?= $e(\App\Presentation\HufFormatter::format($snapshot['one_night_surcharge'] ?? '0.00')) ?></dd></div><div><dt>Időszakos árak</dt><dd><?= $e(implode(', ', $snapshot['applied_date_override_ids'] ?? [])) ?: 'nincs' ?></dd></div></dl></section><?php endif; ?>
<?php if (!empty($snapshot['line_items'])): ?>
<section aria-labelledby="snapshot-items-title"><h2 id="snapshot-items-title">Ár-pillanatkép tételei</h2>
<div class="table-scroll" tabindex="0" role="region" aria-label="Rögzített ártételek"><table><thead><tr><th>Megnevezés</th><th>Mennyiség</th><th>Egységár</th><th>Összeg</th></tr></thead><tbody>
<?php foreach ($snapshot['line_items'] as $item): ?><tr><td><?= $e($item['description'] ?? $item['type'] ?? '') ?></td><td><?= $e($item['quantity'] ?? '') ?></td><td><?= isset($item['unit_amount']) ? $e(\App\Presentation\HufFormatter::format($item['unit_amount'])) : '—' ?></td><td><?= isset($item['total']) ? $e(\App\Presentation\HufFormatter::format($item['total'])) : '—' ?></td></tr><?php endforeach ?>
</tbody></table></div></section>
<?php endif ?>
<section><h2>Foglalási szabályzat</h2><dl class="facts"><div><dt>Elfogadva</dt><dd><?= $e($booking['booking_policy_accepted_at'] ?? '—') ?></dd></div><div><dt>Verzió</dt><dd><?= $e($booking['booking_policy_version'] ?? '—') ?></dd></div><div><dt>URL</dt><dd><?php if (!empty($booking['booking_policy_url'])): ?><a href="<?= $e($booking['booking_policy_url']) ?>" rel="noopener noreferrer"><?= $e($booking['booking_policy_url']) ?></a><?php else: ?>—<?php endif ?></dd></div></dl></section>
<?php require __DIR__ . '/_nightly-pricing.php'; ?><section><h2>Lemondási feltételek</h2><?php if (isset($cancellationPreview) && $cancellationPreview !== null): ?><dl class="facts"><div><dt>Díjmentes lemondás határideje</dt><dd><?= $e($cancellationPreview->snapshot['free_cancellation_deadline']) ?></dd></div><div><dt>Mai kötbér-előnézet</dt><dd><?= $e(\App\Presentation\HufFormatter::format($cancellationPreview->penaltyAmount)) ?></dd></div><div><dt>Ár-pillanatkép szállásdíja</dt><dd><?= $e(\App\Presentation\HufFormatter::format($cancellationPreview->snapshot['accommodation_fee'])) ?></dd></div><div><dt>Kötbér mértéke</dt><dd><?= $e(\App\Presentation\PercentFormatter::fromDecimalRate($cancellationPreview->penaltyRate)) ?></dd></div></dl><?php else: ?><p>Az előnézethez nem áll rendelkezésre megfelelő ár-pillanatkép.</p><?php endif ?><?php if (!empty($booking['cancelled_at'])): ?><p>A rögzített lemondás: <?= $e($booking['cancelled_at']) ?>; kötbér: <?= $e(\App\Presentation\HufFormatter::format($booking['cancellation_penalty_amount'])) ?>.</p><?php endif ?></section>
<?php if ($booking['status'] === 'pending'): ?>
<section aria-labelledby="payment-request-title">
<h2 id="payment-request-title">Foglalás véglegesítése</h2>
<?php if (!empty($paymentConfigurationError)): ?><p class="alert"><?= $e($paymentConfigurationError) ?></p><?php endif ?>
<?php $payment = $booking['payment_request'] ?? null; $paymentStatus = $payment['status'] ?? null; ?>
<?php $advance = $payment['advance_amount'] ?? $paymentAdvance ?? null; if ($advance !== null): ?>
<p>Előleg: <?= $e(\App\Presentation\HufFormatter::format($advance)) ?></p>
<?php endif ?>
<?php if ($paymentStatus === 'sent'): ?>
<p>Díjbekérő elküldve<?= !empty($payment['sent_at']) ? ': ' . $e($payment['sent_at']) : '' ?></p>
<p>A rendszer nem ellenőrzi automatikusan a banki jóváírást. Az előleg beérkezésének ellenőrzése után erősítse meg a foglalást.</p>
<form method="post" action="/admin/bookings/<?= rawurlencode((string) $booking['reference']) ?>/confirm">
<input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>">
<label for="note-confirm">Admin megjegyzés (opcionális)</label><textarea id="note-confirm" name="admin_note" maxlength="500"></textarea>
<button type="submit">Megerősítés</button>
</form>
<?php else: ?>
<p>A foglalás a díjbekérő sikeres elküldése után erősíthető meg.</p>
<?php if ($paymentStatus === 'failed'): ?><p class="alert">Díjbekérő küldése sikertelen</p><?php endif ?>
<?php if ($paymentStatus === 'processing'): ?>
<p>Díjbekérő küldése folyamatban.</p>
<?php elseif (!empty($booking['legacy_pricing_unavailable'])): ?>
<p class="alert">A régi foglalás rögzített végösszege nem áll rendelkezésre; díjbekérő nem küldhető.</p>
<?php else: ?>
<form method="post" action="/admin/bookings/<?= rawurlencode((string) $booking['reference']) ?>/payment-request">
<input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>">
<button type="submit"><?= $paymentStatus === 'failed' ? 'Díjbekérő újraküldése' : 'Díjbekérő e-mail küldése' ?></button>
</form>
<?php endif; endif ?>
</section>
<?php endif ?>
<?php $allowed=['pending'=>['reject'=>'Elutasítás','invalidate'=>'Érvénytelenítés'],'confirmed'=>['cancel'=>'Lemondás','invalidate'=>'Érvénytelenítés']][$booking['status']] ?? []; if ($allowed): ?><section><h2>Műveletek</h2><div class="actions"><?php foreach ($allowed as $action=>$label): ?><form method="post" action="/admin/bookings/<?= rawurlencode((string)$booking['reference']) ?>/<?= $action ?>"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><label for="note-<?= $action ?>">Admin megjegyzés (opcionális)</label><textarea id="note-<?= $action ?>" name="admin_note" maxlength="500"></textarea><button class="<?= in_array($action,['reject','cancel','invalidate'],true)?'danger':'' ?>" type="submit"><?= $label ?></button></form><?php endforeach ?></div></section><?php endif ?>
<section><h2>Státusztörténet</h2><ol class="timeline"><?php foreach ($booking['status_history'] as $item): ?><li><strong><?= $e($item['old_status'] === null ? 'Létrehozás' : \App\Presentation\BookingStatusLabel::for((string) $item['old_status'])) ?> → <?= $e(\App\Presentation\BookingStatusLabel::for((string) $item['status'])) ?></strong><br><time><?= $e($item['created_at']) ?></time><?php if ($item['admin_note']): ?><p><?= $e(\App\Presentation\BookingHistoryNoteLabel::for((string) $item['admin_note'])) ?></p><?php endif ?></li><?php endforeach ?></ol></section>
<section><h2>E-mail állapot</h2><?php if (!$booking['email_outbox']): ?><p>Nincs e-mail rekord.</p><?php else: ?><ul><?php foreach ($booking['email_outbox'] as $mail): ?><li><?= $e(\App\Presentation\EmailStatusLabel::type((string) $mail['type'])) ?> — <strong><?= $e(\App\Presentation\EmailStatusLabel::for((string) $mail['status'])) ?></strong> (<?= (int)$mail['attempts'] ?> kísérlet)<?php if ($mail['status']==='failed'): ?> <span class="alert-inline">Küldés sikertelen</span><?php endif ?></li><?php endforeach ?></ul><?php if (in_array($booking['status'], ['confirmed','rejected','cancelled'], true) && array_filter($booking['email_outbox'], static fn (array $mail): bool => $mail['status'] === 'failed')): ?><form method="post" action="/admin/bookings/<?= rawurlencode((string)$booking['reference']) ?>/retry-email"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><button type="submit">Sikertelen státuszlevél újraküldése</button></form><?php endif; endif ?></section></article><?php require __DIR__ . '/_layout_end.php'; ?>
