<?php declare(strict_types=1); $e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); $c=$configuration; require __DIR__.'/_layout_start.php'; ?>
<section class="admin-page pricing-page"><p class="eyebrow">Árkezelés</p><h1>Árképzés</h1>
<?php if($error): ?><p class="alert"><?= $e($error) ?></p><?php endif; ?>
<p>A 0–3 éves gyermek szállása ingyenes, ezért nem számít bele az árazási létszámba. A 4 éves vagy idősebb gyermek beleszámít.</p>
<section class="panel"><h2>Alapárak létszám és tartózkodási idő szerint</h2><div class="table-scroll"><table><thead><tr><th>Létszám</th><th>Minimum éjszaka</th><th>Maximum éjszaka</th><th>Ár / éj</th><th>Állapot</th><th>Művelet</th></tr></thead><tbody>
<?php foreach($c->bands as $b): ?><tr><td><?= $b->guestCount ?></td><td><?= $b->minNights ?></td><td><?= $b->maxNights??'—' ?></td><td><?= $e($b->nightlyPrice) ?> Ft</td><td><?= $b->active?'Aktív':'Inaktív' ?></td><td><form class="inline-form" method="post" action="/admin/pricing"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="version" value="<?= $c->version ?>"><input type="hidden" name="action" value="band_toggle"><input type="hidden" name="band_id" value="<?= $b->id ?>"><input type="hidden" name="active" value="<?= $b->active?'0':'1' ?>"><button class="compact" type="submit"><?= $b->active?'Inaktiválás':'Aktiválás' ?></button></form></td></tr><?php endforeach; ?></tbody></table></div>
<details><summary>Új ársáv</summary><form method="post" action="/admin/pricing" class="field-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="version" value="<?= $c->version ?>"><input type="hidden" name="action" value="band"><label>Létszám<input name="guest_count" type="number" min="1" max="4" required></label><label>Minimum éjszaka<input name="min_nights" type="number" min="1" required></label><label>Maximum éjszaka<input name="max_nights" type="number" min="1"></label><label>Ár / éj<input name="nightly_price" inputmode="numeric" required></label><button type="submit">Mentés</button></form></details></section>
<section class="panel"><h2>Egyéjszakás felár</h2><p>Csak pontosan egy éjszakás foglalásnál kerül hozzáadásra, egyszer.</p><form method="post" action="/admin/pricing" class="field-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="version" value="<?= $c->version ?>"><input type="hidden" name="action" value="surcharge"><label>Felár (Ft / foglalás)<input name="amount" inputmode="numeric" value="<?= $e($c->oneNightSurcharge) ?>" required></label><button type="submit">Mentés</button></form></section>
<section class="panel"><h2>Egyedi időszakos árak</h2><div class="table-scroll"><table><thead><tr><th>Időszak</th><th>1 fő</th><th>2 fő</th><th>3 fő</th><th>4 fő</th><th>Állapot</th><th>Művelet</th></tr></thead><tbody><?php foreach($c->overrides as $o): ?><tr><td><?= $e($o->startDate) ?> – <?= $e($o->endDate) ?></td><?php for($i=1;$i<=4;$i++): ?><td><?= $e($o->priceFor($i)) ?> Ft</td><?php endfor; ?><td><?= $o->active?'Aktív':'Inaktív' ?></td><td><form class="inline-form" method="post" action="/admin/pricing"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="version" value="<?= $c->version ?>"><input type="hidden" name="action" value="override_toggle"><input type="hidden" name="override_id" value="<?= $o->id ?>"><input type="hidden" name="active" value="<?= $o->active?'0':'1' ?>"><button class="compact" type="submit"><?= $o->active?'Inaktiválás':'Aktiválás' ?></button></form></td></tr><?php endforeach; ?></tbody></table></div>
<details><summary>Új időszak</summary><form method="post" action="/admin/pricing" class="field-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="version" value="<?= $c->version ?>"><input type="hidden" name="action" value="override"><label>Kezdő dátum<input type="date" name="start_date" required></label><label>Záró dátum<input type="date" name="end_date" required></label><?php for($i=1;$i<=4;$i++): ?><label><?= $i ?> fő / éj<input name="price_<?= $i ?>" inputmode="numeric" required></label><?php endfor; ?><button type="submit">Mentés</button></form></details></section></section>
