<?php declare(strict_types=1); $title='Felhasználók – A Bata'; $e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); require __DIR__.'/_layout_start.php'; ?>
<section class="admin-page"><p class="eyebrow">Adminisztráció</p><h1>Felhasználók</h1>
<?php if ($error !== null): ?><div class="alert" role="alert"><?= $e($error) ?></div><?php endif; ?>
<?php if (!empty($notificationsUpdated)): ?><div class="notice" role="status">A foglalási értesítések beállításai elmentve.</div><?php endif; ?>
<p>Az „Új foglalási igény érkezett” admin értesítést az aktív, kijelölt felhasználók kapják. Ha nincs kijelölt aktív felhasználó, a rendszer a tartalék értesítési címre küld.</p>
<form id="booking-notification-preferences-form" method="post" action="/admin/users/booking-notifications"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"></form>
<div class="users-toolbar"><a class="button-link" href="/admin/users/create">+ Új felhasználó</a><button class="compact" type="submit" form="booking-notification-preferences-form">Mentés</button></div>
<div class="table-scroll" tabindex="0" role="region" aria-label="Admin felhasználók"><table class="users-table"><thead><tr><th>Név</th><th>E-mail-cím</th><th>Állapot</th><th>Foglalási értesítések</th><th>Létrehozva</th><th>Műveletek</th></tr></thead><tbody>
<?php foreach ($users as $user): ?><tr><td data-label="Név"><?= $e($user['name']) ?></td><td data-label="E-mail-cím"><?= $e($user['email']) ?></td><td data-label="Állapot"><?= $user['is_active'] ? 'Aktív' : 'Inaktív' ?></td><td class="user-notification-cell" data-label="Foglalási értesítések"><label class="user-notification-control"><input class="user-notification-checkbox" type="checkbox" form="booking-notification-preferences-form" name="notification_admin_ids[]" value="<?= (int)$user['id'] ?>" aria-label="Foglalási értesítések – <?= $e($user['name']) ?>" <?= $user['receives_booking_notifications'] ? 'checked' : '' ?>><span>Kapja</span></label><?php if (!$user['is_active']): ?><small class="user-notification-note">Inaktív – jelenleg nem kap értesítést</small><?php endif; ?></td><td class="users-created" data-label="Létrehozva"><?= $e($user['created_at']) ?></td><td class="table-actions users-actions"><form method="post" action="/admin/users/<?= (int)$user['id'] ?>/<?= $user['is_active'] ? 'deactivate' : 'activate' ?>"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><button class="compact <?= $user['is_active'] ? 'danger' : '' ?>" type="submit"><?= $user['is_active'] ? 'Inaktiválás' : 'Aktiválás' ?></button></form></td></tr><?php endforeach; ?>
<?php if ($users === []): ?><tr><td colspan="6">Nincs felhasználó.</td></tr><?php endif; ?></tbody></table></div></section><?php require __DIR__.'/_layout_end.php'; ?>
